name: alekcodes
region: fra1

domains:
  - domain: alek.codes
    type: PRIMARY
    

static_sites:
  - name: frontend
    github:
      repo: barealek/alek.codes
      branch: main
      deploy_on_push: true
    routes:
      - path: /
    build_command: npm run build
    environment_slug: node-js
    source_dir: frontend